import sys
print("sys.exit(1)で異常終了させる")
sys.exit(1)